title: SWEN444
baseurl: ""
timezone: America/New_York

future: true
permalink: /:year/:month/:day/:title

group_name: ""
group_members:
  - Bill Dybas
  - Daniel Dang
  - Joshua Shear
  - Brandon Stites
  - Byron Zaharako

# Build settings
markdown: kramdown

sass:
  style: compressed
  sass_dir: _scss
